backend:
  name: github
  repo: figurenone/figurenone   # ✅ This is your GitHub repo
  branch: main                  # ✅ Correct branch

media_folder: "src/assets/images/uploads"  # ✅ Where uploads go in the repo
public_folder: "/assets/images/uploads"    # ✅ How the site sees them

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }