backend:
  name: git-gateway
  branch: main
  identity_url: https://figurenone.netlify.app/.netlify/identity

media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"
site_url: https://figurenone.netlify.app

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }