backend:
  name: github
  repo: figurenone/figurenone-site
  branch: main
  auth_type: implicit

media_folder: "src/assets/Images"
public_folder: "/assets/Images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    format: frontmatter
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "layout", label: "Layout", widget: "string", default: "base.njk" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "site"
    label: "Site Data"
    files:
      - label: "Global Site Settings"
        name: "site"
        file: "src/_data/site.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
